/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AcademicYear } from '../models';
// @ts-ignore
import type { SchoolClass } from '../models';
// @ts-ignore
import type { Section } from '../models';
// @ts-ignore
import type { Subject } from '../models';
/**
 * AcademicStructureControllerApi - axios parameter creator
 */
export const AcademicStructureControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {SchoolClass} schoolClass 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClass: async (schoolId: string, schoolClass: SchoolClass, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('createClass', 'schoolId', schoolId)
            // verify required parameter 'schoolClass' is not null or undefined
            assertParamExists('createClass', 'schoolClass', schoolClass)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/classes`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(schoolClass, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {number} classId 
         * @param {Section} section 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSection: async (schoolId: string, classId: number, section: Section, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('createSection', 'schoolId', schoolId)
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('createSection', 'classId', classId)
            // verify required parameter 'section' is not null or undefined
            assertParamExists('createSection', 'section', section)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/classes/{classId}/sections`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)))
                .replace(`{${"classId"}}`, encodeURIComponent(String(classId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(section, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {Subject} subject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubject: async (schoolId: string, subject: Subject, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('createSubject', 'schoolId', schoolId)
            // verify required parameter 'subject' is not null or undefined
            assertParamExists('createSubject', 'subject', subject)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/subjects`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {AcademicYear} academicYear 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createYear: async (schoolId: string, academicYear: AcademicYear, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('createYear', 'schoolId', schoolId)
            // verify required parameter 'academicYear' is not null or undefined
            assertParamExists('createYear', 'academicYear', academicYear)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/years`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(academicYear, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClasses: async (schoolId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getClasses', 'schoolId', schoolId)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/classes`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {number} classId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSections: async (schoolId: string, classId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getSections', 'schoolId', schoolId)
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('getSections', 'classId', classId)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/classes/{classId}/sections`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)))
                .replace(`{${"classId"}}`, encodeURIComponent(String(classId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubjects: async (schoolId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getSubjects', 'schoolId', schoolId)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/subjects`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getYears: async (schoolId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getYears', 'schoolId', schoolId)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/academic/years`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AcademicStructureControllerApi - functional programming interface
 */
export const AcademicStructureControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AcademicStructureControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {SchoolClass} schoolClass 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createClass(schoolId: string, schoolClass: SchoolClass, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolClass>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createClass(schoolId, schoolClass, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.createClass']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {number} classId 
         * @param {Section} section 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSection(schoolId: string, classId: number, section: Section, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Section>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSection(schoolId, classId, section, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.createSection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {Subject} subject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSubject(schoolId: string, subject: Subject, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSubject(schoolId, subject, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.createSubject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {AcademicYear} academicYear 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createYear(schoolId: string, academicYear: AcademicYear, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AcademicYear>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createYear(schoolId, academicYear, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.createYear']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClasses(schoolId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SchoolClass>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClasses(schoolId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.getClasses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {number} classId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSections(schoolId: string, classId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Section>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSections(schoolId, classId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.getSections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubjects(schoolId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Subject>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubjects(schoolId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.getSubjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getYears(schoolId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AcademicYear>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getYears(schoolId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicStructureControllerApi.getYears']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AcademicStructureControllerApi - factory interface
 */
export const AcademicStructureControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AcademicStructureControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {AcademicStructureControllerApiCreateClassRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClass(requestParameters: AcademicStructureControllerApiCreateClassRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchoolClass> {
            return localVarFp.createClass(requestParameters.schoolId, requestParameters.schoolClass, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiCreateSectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSection(requestParameters: AcademicStructureControllerApiCreateSectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Section> {
            return localVarFp.createSection(requestParameters.schoolId, requestParameters.classId, requestParameters.section, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiCreateSubjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubject(requestParameters: AcademicStructureControllerApiCreateSubjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subject> {
            return localVarFp.createSubject(requestParameters.schoolId, requestParameters.subject, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiCreateYearRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createYear(requestParameters: AcademicStructureControllerApiCreateYearRequest, options?: RawAxiosRequestConfig): AxiosPromise<AcademicYear> {
            return localVarFp.createYear(requestParameters.schoolId, requestParameters.academicYear, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiGetClassesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClasses(requestParameters: AcademicStructureControllerApiGetClassesRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<SchoolClass>> {
            return localVarFp.getClasses(requestParameters.schoolId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiGetSectionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSections(requestParameters: AcademicStructureControllerApiGetSectionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Section>> {
            return localVarFp.getSections(requestParameters.schoolId, requestParameters.classId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiGetSubjectsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubjects(requestParameters: AcademicStructureControllerApiGetSubjectsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Subject>> {
            return localVarFp.getSubjects(requestParameters.schoolId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicStructureControllerApiGetYearsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getYears(requestParameters: AcademicStructureControllerApiGetYearsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<AcademicYear>> {
            return localVarFp.getYears(requestParameters.schoolId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createClass operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiCreateClassRequest {
    readonly schoolId: string

    readonly schoolClass: SchoolClass
}

/**
 * Request parameters for createSection operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiCreateSectionRequest {
    readonly schoolId: string

    readonly classId: number

    readonly section: Section
}

/**
 * Request parameters for createSubject operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiCreateSubjectRequest {
    readonly schoolId: string

    readonly subject: Subject
}

/**
 * Request parameters for createYear operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiCreateYearRequest {
    readonly schoolId: string

    readonly academicYear: AcademicYear
}

/**
 * Request parameters for getClasses operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiGetClassesRequest {
    readonly schoolId: string
}

/**
 * Request parameters for getSections operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiGetSectionsRequest {
    readonly schoolId: string

    readonly classId: number
}

/**
 * Request parameters for getSubjects operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiGetSubjectsRequest {
    readonly schoolId: string
}

/**
 * Request parameters for getYears operation in AcademicStructureControllerApi.
 */
export interface AcademicStructureControllerApiGetYearsRequest {
    readonly schoolId: string
}

/**
 * AcademicStructureControllerApi - object-oriented interface
 */
export class AcademicStructureControllerApi extends BaseAPI {
    /**
     * 
     * @param {AcademicStructureControllerApiCreateClassRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createClass(requestParameters: AcademicStructureControllerApiCreateClassRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).createClass(requestParameters.schoolId, requestParameters.schoolClass, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiCreateSectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSection(requestParameters: AcademicStructureControllerApiCreateSectionRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).createSection(requestParameters.schoolId, requestParameters.classId, requestParameters.section, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiCreateSubjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSubject(requestParameters: AcademicStructureControllerApiCreateSubjectRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).createSubject(requestParameters.schoolId, requestParameters.subject, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiCreateYearRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createYear(requestParameters: AcademicStructureControllerApiCreateYearRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).createYear(requestParameters.schoolId, requestParameters.academicYear, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiGetClassesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClasses(requestParameters: AcademicStructureControllerApiGetClassesRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).getClasses(requestParameters.schoolId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiGetSectionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSections(requestParameters: AcademicStructureControllerApiGetSectionsRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).getSections(requestParameters.schoolId, requestParameters.classId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiGetSubjectsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubjects(requestParameters: AcademicStructureControllerApiGetSubjectsRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).getSubjects(requestParameters.schoolId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicStructureControllerApiGetYearsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getYears(requestParameters: AcademicStructureControllerApiGetYearsRequest, options?: RawAxiosRequestConfig) {
        return AcademicStructureControllerApiFp(this.configuration).getYears(requestParameters.schoolId, options).then((request) => request(this.axios, this.basePath));
    }
}

