/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ClassSubject } from '../models';
// @ts-ignore
import type { ClassSubjectRequest } from '../models';
// @ts-ignore
import type { ExamSchedule } from '../models';
// @ts-ignore
import type { ExamScheduleRequest } from '../models';
// @ts-ignore
import type { ExamTerm } from '../models';
// @ts-ignore
import type { ExamTermRequest } from '../models';
// @ts-ignore
import type { MarkEntryRequest } from '../models';
// @ts-ignore
import type { ReportCardDto } from '../models';
// @ts-ignore
import type { SchoolClass } from '../models';
// @ts-ignore
import type { StudentMarks } from '../models';
// @ts-ignore
import type { Subject } from '../models';
// @ts-ignore
import type { SubjectRequest } from '../models';
/**
 * AcademicControllerApi - axios parameter creator
 */
export const AcademicControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ClassSubjectRequest} classSubjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignSubjectToClass: async (classSubjectRequest: ClassSubjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classSubjectRequest' is not null or undefined
            assertParamExists('assignSubjectToClass', 'classSubjectRequest', classSubjectRequest)
            const localVarPath = `/api/academic/class-subjects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classSubjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubject1: async (subjectRequest: SubjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subjectRequest' is not null or undefined
            assertParamExists('createSubject1', 'subjectRequest', subjectRequest)
            const localVarPath = `/api/academic/subjects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ExamTermRequest} examTermRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTerm: async (examTermRequest: ExamTermRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'examTermRequest' is not null or undefined
            assertParamExists('createTerm', 'examTermRequest', examTermRequest)
            const localVarPath = `/api/academic/terms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(examTermRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteClass: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteClass', 'id', id)
            const localVarPath = `/api/academic/classes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubject: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSubject', 'id', id)
            const localVarPath = `/api/academic/subjects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSubjects: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/academic/subjects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTerms: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/academic/terms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} classId 
         * @param {number} termId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMarksForClass: async (classId: number, termId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('getMarksForClass', 'classId', classId)
            // verify required parameter 'termId' is not null or undefined
            assertParamExists('getMarksForClass', 'termId', termId)
            const localVarPath = `/api/academic/marks/class/{classId}`
                .replace(`{${"classId"}}`, encodeURIComponent(String(classId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (termId !== undefined) {
                localVarQueryParameter['termId'] = termId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} studentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportCard: async (studentId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'studentId' is not null or undefined
            assertParamExists('getReportCard', 'studentId', studentId)
            const localVarPath = `/api/academic/reports/{studentId}`
                .replace(`{${"studentId"}}`, encodeURIComponent(String(studentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MarkEntryRequest} markEntryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveStudentMarks: async (markEntryRequest: MarkEntryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'markEntryRequest' is not null or undefined
            assertParamExists('saveStudentMarks', 'markEntryRequest', markEntryRequest)
            const localVarPath = `/api/academic/marks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(markEntryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ExamScheduleRequest} examScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scheduleExam: async (examScheduleRequest: ExamScheduleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'examScheduleRequest' is not null or undefined
            assertParamExists('scheduleExam', 'examScheduleRequest', examScheduleRequest)
            const localVarPath = `/api/academic/schedules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(examScheduleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {{ [key: string]: string; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateClass: async (id: number, requestBody: { [key: string]: string; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateClass', 'id', id)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('updateClass', 'requestBody', requestBody)
            const localVarPath = `/api/academic/classes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubject: async (id: number, subjectRequest: SubjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSubject', 'id', id)
            // verify required parameter 'subjectRequest' is not null or undefined
            assertParamExists('updateSubject', 'subjectRequest', subjectRequest)
            const localVarPath = `/api/academic/subjects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AcademicControllerApi - functional programming interface
 */
export const AcademicControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AcademicControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ClassSubjectRequest} classSubjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignSubjectToClass(classSubjectRequest: ClassSubjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClassSubject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignSubjectToClass(classSubjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.assignSubjectToClass']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSubject1(subjectRequest: SubjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSubject1(subjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.createSubject1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ExamTermRequest} examTermRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTerm(examTermRequest: ExamTermRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExamTerm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTerm(examTermRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.createTerm']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteClass(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteClass(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.deleteClass']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubject(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubject(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.deleteSubject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSubjects(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Subject>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSubjects(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.getAllSubjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTerms(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExamTerm>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTerms(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.getAllTerms']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} classId 
         * @param {number} termId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMarksForClass(classId: number, termId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ReportCardDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMarksForClass(classId, termId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.getMarksForClass']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} studentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReportCard(studentId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportCardDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReportCard(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.getReportCard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {MarkEntryRequest} markEntryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveStudentMarks(markEntryRequest: MarkEntryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StudentMarks>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveStudentMarks(markEntryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.saveStudentMarks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ExamScheduleRequest} examScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async scheduleExam(examScheduleRequest: ExamScheduleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExamSchedule>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.scheduleExam(examScheduleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.scheduleExam']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {{ [key: string]: string; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateClass(id: number, requestBody: { [key: string]: string; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolClass>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateClass(id, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.updateClass']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {SubjectRequest} subjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSubject(id: number, subjectRequest: SubjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSubject(id, subjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AcademicControllerApi.updateSubject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AcademicControllerApi - factory interface
 */
export const AcademicControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AcademicControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {AcademicControllerApiAssignSubjectToClassRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignSubjectToClass(requestParameters: AcademicControllerApiAssignSubjectToClassRequest, options?: RawAxiosRequestConfig): AxiosPromise<ClassSubject> {
            return localVarFp.assignSubjectToClass(requestParameters.classSubjectRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiCreateSubject1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubject1(requestParameters: AcademicControllerApiCreateSubject1Request, options?: RawAxiosRequestConfig): AxiosPromise<Subject> {
            return localVarFp.createSubject1(requestParameters.subjectRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiCreateTermRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTerm(requestParameters: AcademicControllerApiCreateTermRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExamTerm> {
            return localVarFp.createTerm(requestParameters.examTermRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiDeleteClassRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteClass(requestParameters: AcademicControllerApiDeleteClassRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteClass(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiDeleteSubjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubject(requestParameters: AcademicControllerApiDeleteSubjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSubject(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSubjects(options?: RawAxiosRequestConfig): AxiosPromise<Array<Subject>> {
            return localVarFp.getAllSubjects(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTerms(options?: RawAxiosRequestConfig): AxiosPromise<Array<ExamTerm>> {
            return localVarFp.getAllTerms(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiGetMarksForClassRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMarksForClass(requestParameters: AcademicControllerApiGetMarksForClassRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ReportCardDto>> {
            return localVarFp.getMarksForClass(requestParameters.classId, requestParameters.termId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiGetReportCardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportCard(requestParameters: AcademicControllerApiGetReportCardRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportCardDto> {
            return localVarFp.getReportCard(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiSaveStudentMarksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveStudentMarks(requestParameters: AcademicControllerApiSaveStudentMarksRequest, options?: RawAxiosRequestConfig): AxiosPromise<StudentMarks> {
            return localVarFp.saveStudentMarks(requestParameters.markEntryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiScheduleExamRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scheduleExam(requestParameters: AcademicControllerApiScheduleExamRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExamSchedule> {
            return localVarFp.scheduleExam(requestParameters.examScheduleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiUpdateClassRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateClass(requestParameters: AcademicControllerApiUpdateClassRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchoolClass> {
            return localVarFp.updateClass(requestParameters.id, requestParameters.requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AcademicControllerApiUpdateSubjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubject(requestParameters: AcademicControllerApiUpdateSubjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subject> {
            return localVarFp.updateSubject(requestParameters.id, requestParameters.subjectRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for assignSubjectToClass operation in AcademicControllerApi.
 */
export interface AcademicControllerApiAssignSubjectToClassRequest {
    readonly classSubjectRequest: ClassSubjectRequest
}

/**
 * Request parameters for createSubject1 operation in AcademicControllerApi.
 */
export interface AcademicControllerApiCreateSubject1Request {
    readonly subjectRequest: SubjectRequest
}

/**
 * Request parameters for createTerm operation in AcademicControllerApi.
 */
export interface AcademicControllerApiCreateTermRequest {
    readonly examTermRequest: ExamTermRequest
}

/**
 * Request parameters for deleteClass operation in AcademicControllerApi.
 */
export interface AcademicControllerApiDeleteClassRequest {
    readonly id: number
}

/**
 * Request parameters for deleteSubject operation in AcademicControllerApi.
 */
export interface AcademicControllerApiDeleteSubjectRequest {
    readonly id: number
}

/**
 * Request parameters for getMarksForClass operation in AcademicControllerApi.
 */
export interface AcademicControllerApiGetMarksForClassRequest {
    readonly classId: number

    readonly termId: number
}

/**
 * Request parameters for getReportCard operation in AcademicControllerApi.
 */
export interface AcademicControllerApiGetReportCardRequest {
    readonly studentId: number
}

/**
 * Request parameters for saveStudentMarks operation in AcademicControllerApi.
 */
export interface AcademicControllerApiSaveStudentMarksRequest {
    readonly markEntryRequest: MarkEntryRequest
}

/**
 * Request parameters for scheduleExam operation in AcademicControllerApi.
 */
export interface AcademicControllerApiScheduleExamRequest {
    readonly examScheduleRequest: ExamScheduleRequest
}

/**
 * Request parameters for updateClass operation in AcademicControllerApi.
 */
export interface AcademicControllerApiUpdateClassRequest {
    readonly id: number

    readonly requestBody: { [key: string]: string; }
}

/**
 * Request parameters for updateSubject operation in AcademicControllerApi.
 */
export interface AcademicControllerApiUpdateSubjectRequest {
    readonly id: number

    readonly subjectRequest: SubjectRequest
}

/**
 * AcademicControllerApi - object-oriented interface
 */
export class AcademicControllerApi extends BaseAPI {
    /**
     * 
     * @param {AcademicControllerApiAssignSubjectToClassRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignSubjectToClass(requestParameters: AcademicControllerApiAssignSubjectToClassRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).assignSubjectToClass(requestParameters.classSubjectRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiCreateSubject1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSubject1(requestParameters: AcademicControllerApiCreateSubject1Request, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).createSubject1(requestParameters.subjectRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiCreateTermRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTerm(requestParameters: AcademicControllerApiCreateTermRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).createTerm(requestParameters.examTermRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiDeleteClassRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteClass(requestParameters: AcademicControllerApiDeleteClassRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).deleteClass(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiDeleteSubjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSubject(requestParameters: AcademicControllerApiDeleteSubjectRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).deleteSubject(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllSubjects(options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).getAllSubjects(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllTerms(options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).getAllTerms(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiGetMarksForClassRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMarksForClass(requestParameters: AcademicControllerApiGetMarksForClassRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).getMarksForClass(requestParameters.classId, requestParameters.termId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiGetReportCardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getReportCard(requestParameters: AcademicControllerApiGetReportCardRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).getReportCard(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiSaveStudentMarksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public saveStudentMarks(requestParameters: AcademicControllerApiSaveStudentMarksRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).saveStudentMarks(requestParameters.markEntryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiScheduleExamRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public scheduleExam(requestParameters: AcademicControllerApiScheduleExamRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).scheduleExam(requestParameters.examScheduleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiUpdateClassRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateClass(requestParameters: AcademicControllerApiUpdateClassRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).updateClass(requestParameters.id, requestParameters.requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AcademicControllerApiUpdateSubjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSubject(requestParameters: AcademicControllerApiUpdateSubjectRequest, options?: RawAxiosRequestConfig) {
        return AcademicControllerApiFp(this.configuration).updateSubject(requestParameters.id, requestParameters.subjectRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

