/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CollectionTrendDto } from '../models';
// @ts-ignore
import type { FinancialSummaryDto } from '../models';
// @ts-ignore
import type { ReportCardDataDto } from '../models';
/**
 * AnalyticsControllerApi - axios parameter creator
 */
export const AnalyticsControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [days] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCollectionTrend: async (days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analytics/finance/trend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFinancialSummary: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/analytics/finance/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} studentId 
         * @param {number} termId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportCardData: async (studentId: number, termId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'studentId' is not null or undefined
            assertParamExists('getReportCardData', 'studentId', studentId)
            // verify required parameter 'termId' is not null or undefined
            assertParamExists('getReportCardData', 'termId', termId)
            const localVarPath = `/api/analytics/report-card/{studentId}`
                .replace(`{${"studentId"}}`, encodeURIComponent(String(studentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (termId !== undefined) {
                localVarQueryParameter['termId'] = termId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalyticsControllerApi - functional programming interface
 */
export const AnalyticsControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AnalyticsControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [days] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCollectionTrend(days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CollectionTrendDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCollectionTrend(days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsControllerApi.getCollectionTrend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFinancialSummary(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialSummaryDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFinancialSummary(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsControllerApi.getFinancialSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} studentId 
         * @param {number} termId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReportCardData(studentId: number, termId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportCardDataDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReportCardData(studentId, termId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsControllerApi.getReportCardData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AnalyticsControllerApi - factory interface
 */
export const AnalyticsControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AnalyticsControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {AnalyticsControllerApiGetCollectionTrendRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCollectionTrend(requestParameters: AnalyticsControllerApiGetCollectionTrendRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CollectionTrendDto>> {
            return localVarFp.getCollectionTrend(requestParameters.days, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFinancialSummary(options?: RawAxiosRequestConfig): AxiosPromise<FinancialSummaryDto> {
            return localVarFp.getFinancialSummary(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AnalyticsControllerApiGetReportCardDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportCardData(requestParameters: AnalyticsControllerApiGetReportCardDataRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportCardDataDto> {
            return localVarFp.getReportCardData(requestParameters.studentId, requestParameters.termId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCollectionTrend operation in AnalyticsControllerApi.
 */
export interface AnalyticsControllerApiGetCollectionTrendRequest {
    readonly days?: number
}

/**
 * Request parameters for getReportCardData operation in AnalyticsControllerApi.
 */
export interface AnalyticsControllerApiGetReportCardDataRequest {
    readonly studentId: number

    readonly termId: number
}

/**
 * AnalyticsControllerApi - object-oriented interface
 */
export class AnalyticsControllerApi extends BaseAPI {
    /**
     * 
     * @param {AnalyticsControllerApiGetCollectionTrendRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCollectionTrend(requestParameters: AnalyticsControllerApiGetCollectionTrendRequest = {}, options?: RawAxiosRequestConfig) {
        return AnalyticsControllerApiFp(this.configuration).getCollectionTrend(requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFinancialSummary(options?: RawAxiosRequestConfig) {
        return AnalyticsControllerApiFp(this.configuration).getFinancialSummary(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AnalyticsControllerApiGetReportCardDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getReportCardData(requestParameters: AnalyticsControllerApiGetReportCardDataRequest, options?: RawAxiosRequestConfig) {
        return AnalyticsControllerApiFp(this.configuration).getReportCardData(requestParameters.studentId, requestParameters.termId, options).then((request) => request(this.axios, this.basePath));
    }
}

