/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AttendanceRecord } from '../models';
// @ts-ignore
import type { AttendanceRecordDto } from '../models';
// @ts-ignore
import type { AttendanceSummaryDto } from '../models';
// @ts-ignore
import type { BulkMarkAttendanceRequest } from '../models';
// @ts-ignore
import type { BulkMarkAttendanceResponse } from '../models';
// @ts-ignore
import type { ClassAttendanceSheetDto } from '../models';
// @ts-ignore
import type { ClassAttendanceStatistics } from '../models';
// @ts-ignore
import type { MarkAttendanceRequest } from '../models';
// @ts-ignore
import type { UpdateAttendanceRequest } from '../models';
/**
 * AttendanceControllerApi - axios parameter creator
 */
export const AttendanceControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} classId 
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClassAttendanceSheet: async (classId: number, date: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('getClassAttendanceSheet', 'classId', classId)
            // verify required parameter 'date' is not null or undefined
            assertParamExists('getClassAttendanceSheet', 'date', date)
            const localVarPath = `/api/attendance/class/{classId}/date/{date}`
                .replace(`{${"classId"}}`, encodeURIComponent(String(classId)))
                .replace(`{${"date"}}`, encodeURIComponent(String(date)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} classId 
         * @param {string} startDate 
         * @param {string} endDate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClassAttendanceStatistics: async (classId: number, startDate: string, endDate: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('getClassAttendanceStatistics', 'classId', classId)
            // verify required parameter 'startDate' is not null or undefined
            assertParamExists('getClassAttendanceStatistics', 'startDate', startDate)
            // verify required parameter 'endDate' is not null or undefined
            assertParamExists('getClassAttendanceStatistics', 'endDate', endDate)
            const localVarPath = `/api/attendance/class/{classId}/statistics`
                .replace(`{${"classId"}}`, encodeURIComponent(String(classId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} studentId 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentAttendanceHistory: async (studentId: number, startDate?: string, endDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'studentId' is not null or undefined
            assertParamExists('getStudentAttendanceHistory', 'studentId', studentId)
            const localVarPath = `/api/attendance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} studentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentAttendanceSummary: async (studentId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'studentId' is not null or undefined
            assertParamExists('getStudentAttendanceSummary', 'studentId', studentId)
            const localVarPath = `/api/attendance/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {MarkAttendanceRequest} markAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAttendance: async (markAttendanceRequest: MarkAttendanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'markAttendanceRequest' is not null or undefined
            assertParamExists('markAttendance', 'markAttendanceRequest', markAttendanceRequest)
            const localVarPath = `/api/attendance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(markAttendanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {BulkMarkAttendanceRequest} bulkMarkAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markBulkAttendance: async (bulkMarkAttendanceRequest: BulkMarkAttendanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkMarkAttendanceRequest' is not null or undefined
            assertParamExists('markBulkAttendance', 'bulkMarkAttendanceRequest', bulkMarkAttendanceRequest)
            const localVarPath = `/api/attendance/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkMarkAttendanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {UpdateAttendanceRequest} updateAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAttendance: async (id: number, updateAttendanceRequest: UpdateAttendanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAttendance', 'id', id)
            // verify required parameter 'updateAttendanceRequest' is not null or undefined
            assertParamExists('updateAttendance', 'updateAttendanceRequest', updateAttendanceRequest)
            const localVarPath = `/api/attendance/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAttendanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AttendanceControllerApi - functional programming interface
 */
export const AttendanceControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AttendanceControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} classId 
         * @param {string} date 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClassAttendanceSheet(classId: number, date: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClassAttendanceSheetDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClassAttendanceSheet(classId, date, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.getClassAttendanceSheet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} classId 
         * @param {string} startDate 
         * @param {string} endDate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClassAttendanceStatistics(classId: number, startDate: string, endDate: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClassAttendanceStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClassAttendanceStatistics(classId, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.getClassAttendanceStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} studentId 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStudentAttendanceHistory(studentId: number, startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttendanceRecordDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStudentAttendanceHistory(studentId, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.getStudentAttendanceHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} studentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStudentAttendanceSummary(studentId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttendanceSummaryDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStudentAttendanceSummary(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.getStudentAttendanceSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {MarkAttendanceRequest} markAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markAttendance(markAttendanceRequest: MarkAttendanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttendanceRecord>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markAttendance(markAttendanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.markAttendance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {BulkMarkAttendanceRequest} bulkMarkAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markBulkAttendance(bulkMarkAttendanceRequest: BulkMarkAttendanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkMarkAttendanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markBulkAttendance(bulkMarkAttendanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.markBulkAttendance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {UpdateAttendanceRequest} updateAttendanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAttendance(id: number, updateAttendanceRequest: UpdateAttendanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttendanceRecordDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAttendance(id, updateAttendanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceControllerApi.updateAttendance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AttendanceControllerApi - factory interface
 */
export const AttendanceControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AttendanceControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {AttendanceControllerApiGetClassAttendanceSheetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClassAttendanceSheet(requestParameters: AttendanceControllerApiGetClassAttendanceSheetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ClassAttendanceSheetDto> {
            return localVarFp.getClassAttendanceSheet(requestParameters.classId, requestParameters.date, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AttendanceControllerApiGetClassAttendanceStatisticsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClassAttendanceStatistics(requestParameters: AttendanceControllerApiGetClassAttendanceStatisticsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ClassAttendanceStatistics> {
            return localVarFp.getClassAttendanceStatistics(requestParameters.classId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AttendanceControllerApiGetStudentAttendanceHistoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentAttendanceHistory(requestParameters: AttendanceControllerApiGetStudentAttendanceHistoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<AttendanceRecordDto>> {
            return localVarFp.getStudentAttendanceHistory(requestParameters.studentId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AttendanceControllerApiGetStudentAttendanceSummaryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentAttendanceSummary(requestParameters: AttendanceControllerApiGetStudentAttendanceSummaryRequest, options?: RawAxiosRequestConfig): AxiosPromise<AttendanceSummaryDto> {
            return localVarFp.getStudentAttendanceSummary(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AttendanceControllerApiMarkAttendanceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAttendance(requestParameters: AttendanceControllerApiMarkAttendanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<AttendanceRecord> {
            return localVarFp.markAttendance(requestParameters.markAttendanceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AttendanceControllerApiMarkBulkAttendanceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markBulkAttendance(requestParameters: AttendanceControllerApiMarkBulkAttendanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<BulkMarkAttendanceResponse> {
            return localVarFp.markBulkAttendance(requestParameters.bulkMarkAttendanceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AttendanceControllerApiUpdateAttendanceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAttendance(requestParameters: AttendanceControllerApiUpdateAttendanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<AttendanceRecordDto> {
            return localVarFp.updateAttendance(requestParameters.id, requestParameters.updateAttendanceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getClassAttendanceSheet operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiGetClassAttendanceSheetRequest {
    readonly classId: number

    readonly date: string
}

/**
 * Request parameters for getClassAttendanceStatistics operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiGetClassAttendanceStatisticsRequest {
    readonly classId: number

    readonly startDate: string

    readonly endDate: string
}

/**
 * Request parameters for getStudentAttendanceHistory operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiGetStudentAttendanceHistoryRequest {
    readonly studentId: number

    readonly startDate?: string

    readonly endDate?: string
}

/**
 * Request parameters for getStudentAttendanceSummary operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiGetStudentAttendanceSummaryRequest {
    readonly studentId: number
}

/**
 * Request parameters for markAttendance operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiMarkAttendanceRequest {
    readonly markAttendanceRequest: MarkAttendanceRequest
}

/**
 * Request parameters for markBulkAttendance operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiMarkBulkAttendanceRequest {
    readonly bulkMarkAttendanceRequest: BulkMarkAttendanceRequest
}

/**
 * Request parameters for updateAttendance operation in AttendanceControllerApi.
 */
export interface AttendanceControllerApiUpdateAttendanceRequest {
    readonly id: number

    readonly updateAttendanceRequest: UpdateAttendanceRequest
}

/**
 * AttendanceControllerApi - object-oriented interface
 */
export class AttendanceControllerApi extends BaseAPI {
    /**
     * 
     * @param {AttendanceControllerApiGetClassAttendanceSheetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClassAttendanceSheet(requestParameters: AttendanceControllerApiGetClassAttendanceSheetRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).getClassAttendanceSheet(requestParameters.classId, requestParameters.date, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AttendanceControllerApiGetClassAttendanceStatisticsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getClassAttendanceStatistics(requestParameters: AttendanceControllerApiGetClassAttendanceStatisticsRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).getClassAttendanceStatistics(requestParameters.classId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AttendanceControllerApiGetStudentAttendanceHistoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStudentAttendanceHistory(requestParameters: AttendanceControllerApiGetStudentAttendanceHistoryRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).getStudentAttendanceHistory(requestParameters.studentId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AttendanceControllerApiGetStudentAttendanceSummaryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStudentAttendanceSummary(requestParameters: AttendanceControllerApiGetStudentAttendanceSummaryRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).getStudentAttendanceSummary(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AttendanceControllerApiMarkAttendanceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markAttendance(requestParameters: AttendanceControllerApiMarkAttendanceRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).markAttendance(requestParameters.markAttendanceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AttendanceControllerApiMarkBulkAttendanceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markBulkAttendance(requestParameters: AttendanceControllerApiMarkBulkAttendanceRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).markBulkAttendance(requestParameters.bulkMarkAttendanceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AttendanceControllerApiUpdateAttendanceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateAttendance(requestParameters: AttendanceControllerApiUpdateAttendanceRequest, options?: RawAxiosRequestConfig) {
        return AttendanceControllerApiFp(this.configuration).updateAttendance(requestParameters.id, requestParameters.updateAttendanceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

