/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Homework } from '../models';
// @ts-ignore
import type { HomeworkRequest } from '../models';
/**
 * HomeworkControllerApi - axios parameter creator
 */
export const HomeworkControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {HomeworkRequest} homeworkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHomework: async (homeworkRequest: HomeworkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeworkRequest' is not null or undefined
            assertParamExists('createHomework', 'homeworkRequest', homeworkRequest)
            const localVarPath = `/api/homework`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(homeworkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHomework: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteHomework', 'id', id)
            const localVarPath = `/api/homework/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllHomework: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/homework`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {HomeworkRequest} homeworkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateHomework: async (id: number, homeworkRequest: HomeworkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateHomework', 'id', id)
            // verify required parameter 'homeworkRequest' is not null or undefined
            assertParamExists('updateHomework', 'homeworkRequest', homeworkRequest)
            const localVarPath = `/api/homework/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(homeworkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeworkControllerApi - functional programming interface
 */
export const HomeworkControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HomeworkControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {HomeworkRequest} homeworkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createHomework(homeworkRequest: HomeworkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Homework>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createHomework(homeworkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeworkControllerApi.createHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteHomework(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteHomework(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeworkControllerApi.deleteHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllHomework(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Homework>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllHomework(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeworkControllerApi.getAllHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {HomeworkRequest} homeworkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateHomework(id: number, homeworkRequest: HomeworkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Homework>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateHomework(id, homeworkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeworkControllerApi.updateHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HomeworkControllerApi - factory interface
 */
export const HomeworkControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HomeworkControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {HomeworkControllerApiCreateHomeworkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHomework(requestParameters: HomeworkControllerApiCreateHomeworkRequest, options?: RawAxiosRequestConfig): AxiosPromise<Homework> {
            return localVarFp.createHomework(requestParameters.homeworkRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HomeworkControllerApiDeleteHomeworkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHomework(requestParameters: HomeworkControllerApiDeleteHomeworkRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteHomework(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllHomework(options?: RawAxiosRequestConfig): AxiosPromise<Array<Homework>> {
            return localVarFp.getAllHomework(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HomeworkControllerApiUpdateHomeworkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateHomework(requestParameters: HomeworkControllerApiUpdateHomeworkRequest, options?: RawAxiosRequestConfig): AxiosPromise<Homework> {
            return localVarFp.updateHomework(requestParameters.id, requestParameters.homeworkRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createHomework operation in HomeworkControllerApi.
 */
export interface HomeworkControllerApiCreateHomeworkRequest {
    readonly homeworkRequest: HomeworkRequest
}

/**
 * Request parameters for deleteHomework operation in HomeworkControllerApi.
 */
export interface HomeworkControllerApiDeleteHomeworkRequest {
    readonly id: number
}

/**
 * Request parameters for updateHomework operation in HomeworkControllerApi.
 */
export interface HomeworkControllerApiUpdateHomeworkRequest {
    readonly id: number

    readonly homeworkRequest: HomeworkRequest
}

/**
 * HomeworkControllerApi - object-oriented interface
 */
export class HomeworkControllerApi extends BaseAPI {
    /**
     * 
     * @param {HomeworkControllerApiCreateHomeworkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createHomework(requestParameters: HomeworkControllerApiCreateHomeworkRequest, options?: RawAxiosRequestConfig) {
        return HomeworkControllerApiFp(this.configuration).createHomework(requestParameters.homeworkRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HomeworkControllerApiDeleteHomeworkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteHomework(requestParameters: HomeworkControllerApiDeleteHomeworkRequest, options?: RawAxiosRequestConfig) {
        return HomeworkControllerApiFp(this.configuration).deleteHomework(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllHomework(options?: RawAxiosRequestConfig) {
        return HomeworkControllerApiFp(this.configuration).getAllHomework(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HomeworkControllerApiUpdateHomeworkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateHomework(requestParameters: HomeworkControllerApiUpdateHomeworkRequest, options?: RawAxiosRequestConfig) {
        return HomeworkControllerApiFp(this.configuration).updateHomework(requestParameters.id, requestParameters.homeworkRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

