/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ImportJob } from '../models';
// @ts-ignore
import type { UploadImportRequest } from '../models';
/**
 * ImportControllerApi - axios parameter creator
 */
export const ImportControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {UploadImportTypeEnum} type 
         * @param {UploadImportRequest} [uploadImportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImport: async (schoolId: string, type: UploadImportTypeEnum, uploadImportRequest?: UploadImportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('uploadImport', 'schoolId', schoolId)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('uploadImport', 'type', type)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/imports`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadImportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImportControllerApi - functional programming interface
 */
export const ImportControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImportControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {UploadImportTypeEnum} type 
         * @param {UploadImportRequest} [uploadImportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadImport(schoolId: string, type: UploadImportTypeEnum, uploadImportRequest?: UploadImportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportJob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadImport(schoolId, type, uploadImportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImportControllerApi.uploadImport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ImportControllerApi - factory interface
 */
export const ImportControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImportControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ImportControllerApiUploadImportRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImport(requestParameters: ImportControllerApiUploadImportRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportJob> {
            return localVarFp.uploadImport(requestParameters.schoolId, requestParameters.type, requestParameters.uploadImportRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for uploadImport operation in ImportControllerApi.
 */
export interface ImportControllerApiUploadImportRequest {
    readonly schoolId: string

    readonly type: UploadImportTypeEnum

    readonly uploadImportRequest?: UploadImportRequest
}

/**
 * ImportControllerApi - object-oriented interface
 */
export class ImportControllerApi extends BaseAPI {
    /**
     * 
     * @param {ImportControllerApiUploadImportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadImport(requestParameters: ImportControllerApiUploadImportRequest, options?: RawAxiosRequestConfig) {
        return ImportControllerApiFp(this.configuration).uploadImport(requestParameters.schoolId, requestParameters.type, requestParameters.uploadImportRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const UploadImportTypeEnum = {
    Student: 'STUDENT',
    Teacher: 'TEACHER',
    Parent: 'PARENT'
} as const;
export type UploadImportTypeEnum = typeof UploadImportTypeEnum[keyof typeof UploadImportTypeEnum];
