/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResultString } from '../models';
// @ts-ignore
import type { ApiResultTokenRegistrationResponse } from '../models';
// @ts-ignore
import type { NotificationTokenDto } from '../models';
/**
 * NotificationControllerApi - axios parameter creator
 */
export const NotificationControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {NotificationTokenDto} notificationTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerToken: async (notificationTokenDto: NotificationTokenDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'notificationTokenDto' is not null or undefined
            assertParamExists('registerToken', 'notificationTokenDto', notificationTokenDto)
            const localVarPath = `/api/notifications/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(notificationTokenDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {NotificationTokenDto} notificationTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unregisterToken: async (notificationTokenDto: NotificationTokenDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'notificationTokenDto' is not null or undefined
            assertParamExists('unregisterToken', 'notificationTokenDto', notificationTokenDto)
            const localVarPath = `/api/notifications/unregister`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(notificationTokenDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationControllerApi - functional programming interface
 */
export const NotificationControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {NotificationTokenDto} notificationTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerToken(notificationTokenDto: NotificationTokenDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultTokenRegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerToken(notificationTokenDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationControllerApi.registerToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {NotificationTokenDto} notificationTokenDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unregisterToken(notificationTokenDto: NotificationTokenDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unregisterToken(notificationTokenDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationControllerApi.unregisterToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationControllerApi - factory interface
 */
export const NotificationControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {NotificationControllerApiRegisterTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerToken(requestParameters: NotificationControllerApiRegisterTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultTokenRegistrationResponse> {
            return localVarFp.registerToken(requestParameters.notificationTokenDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {NotificationControllerApiUnregisterTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unregisterToken(requestParameters: NotificationControllerApiUnregisterTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultString> {
            return localVarFp.unregisterToken(requestParameters.notificationTokenDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for registerToken operation in NotificationControllerApi.
 */
export interface NotificationControllerApiRegisterTokenRequest {
    readonly notificationTokenDto: NotificationTokenDto
}

/**
 * Request parameters for unregisterToken operation in NotificationControllerApi.
 */
export interface NotificationControllerApiUnregisterTokenRequest {
    readonly notificationTokenDto: NotificationTokenDto
}

/**
 * NotificationControllerApi - object-oriented interface
 */
export class NotificationControllerApi extends BaseAPI {
    /**
     * 
     * @param {NotificationControllerApiRegisterTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerToken(requestParameters: NotificationControllerApiRegisterTokenRequest, options?: RawAxiosRequestConfig) {
        return NotificationControllerApiFp(this.configuration).registerToken(requestParameters.notificationTokenDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {NotificationControllerApiUnregisterTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unregisterToken(requestParameters: NotificationControllerApiUnregisterTokenRequest, options?: RawAxiosRequestConfig) {
        return NotificationControllerApiFp(this.configuration).unregisterToken(requestParameters.notificationTokenDto, options).then((request) => request(this.axios, this.basePath));
    }
}

