/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResultAttendanceSummaryDto } from '../models';
// @ts-ignore
import type { ApiResultDashboardDto } from '../models';
// @ts-ignore
import type { ApiResultHomeworkListDto } from '../models';
// @ts-ignore
import type { ApiResultHomeworkSubmissionDto } from '../models';
// @ts-ignore
import type { ApiResultListAttendanceRecordDto } from '../models';
// @ts-ignore
import type { ApiResultListLinkedStudentDto } from '../models';
// @ts-ignore
import type { ApiResultPresignedUrlDto } from '../models';
// @ts-ignore
import type { ApiResultResultsDto } from '../models';
// @ts-ignore
import type { ApiResultStudentLedgerDto } from '../models';
// @ts-ignore
import type { ApiResultTimetableDto } from '../models';
// @ts-ignore
import type { ApiResultUserProfileDto } from '../models';
// @ts-ignore
import type { SubmitHomeworkRequest } from '../models';
/**
 * ProfileControllerApi - axios parameter creator
 */
export const ProfileControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} homeworkId 
         * @param {string} fileName 
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateHomeworkUploadUrl: async (homeworkId: number, fileName: string, contentType: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeworkId' is not null or undefined
            assertParamExists('generateHomeworkUploadUrl', 'homeworkId', homeworkId)
            // verify required parameter 'fileName' is not null or undefined
            assertParamExists('generateHomeworkUploadUrl', 'fileName', fileName)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('generateHomeworkUploadUrl', 'contentType', contentType)
            const localVarPath = `/api/me/homework/{homeworkId}/upload-url`
                .replace(`{${"homeworkId"}}`, encodeURIComponent(String(homeworkId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (fileName !== undefined) {
                localVarQueryParameter['fileName'] = fileName;
            }

            if (contentType !== undefined) {
                localVarQueryParameter['contentType'] = contentType;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendanceHistory: async (studentId?: number, startDate?: string, endDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/attendance/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendanceSummary: async (studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/attendance/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboard: async (studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/home`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeeLedger: async (studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/fees/ledger`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHomework: async (studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/homework`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} homeworkId 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHomeworkSubmission: async (homeworkId: number, studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeworkId' is not null or undefined
            assertParamExists('getHomeworkSubmission', 'homeworkId', homeworkId)
            const localVarPath = `/api/me/homework/{homeworkId}/submission`
                .replace(`{${"homeworkId"}}`, encodeURIComponent(String(homeworkId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLinkedStudents: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/students`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResults: async (studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/results`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimetable: async (studentId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/me/timetable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (studentId !== undefined) {
                localVarQueryParameter['studentId'] = studentId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} homeworkId 
         * @param {SubmitHomeworkRequest} submitHomeworkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitHomework: async (homeworkId: number, submitHomeworkRequest: SubmitHomeworkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeworkId' is not null or undefined
            assertParamExists('submitHomework', 'homeworkId', homeworkId)
            // verify required parameter 'submitHomeworkRequest' is not null or undefined
            assertParamExists('submitHomework', 'submitHomeworkRequest', submitHomeworkRequest)
            const localVarPath = `/api/me/homework/{homeworkId}/submit`
                .replace(`{${"homeworkId"}}`, encodeURIComponent(String(homeworkId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitHomeworkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProfileControllerApi - functional programming interface
 */
export const ProfileControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProfileControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} homeworkId 
         * @param {string} fileName 
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateHomeworkUploadUrl(homeworkId: number, fileName: string, contentType: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultPresignedUrlDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateHomeworkUploadUrl(homeworkId, fileName, contentType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.generateHomeworkUploadUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {string} [startDate] 
         * @param {string} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttendanceHistory(studentId?: number, startDate?: string, endDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultListAttendanceRecordDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttendanceHistory(studentId, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getAttendanceHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAttendanceSummary(studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultAttendanceSummaryDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAttendanceSummary(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getAttendanceSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultUserProfileDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboard(studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultDashboardDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboard(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeeLedger(studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultStudentLedgerDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeeLedger(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getFeeLedger']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHomework(studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultHomeworkListDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHomework(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} homeworkId 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHomeworkSubmission(homeworkId: number, studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultHomeworkSubmissionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHomeworkSubmission(homeworkId, studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getHomeworkSubmission']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLinkedStudents(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultListLinkedStudentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLinkedStudents(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getLinkedStudents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getResults(studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultResultsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getResults(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getResults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [studentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTimetable(studentId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultTimetableDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTimetable(studentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.getTimetable']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} homeworkId 
         * @param {SubmitHomeworkRequest} submitHomeworkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitHomework(homeworkId: number, submitHomeworkRequest: SubmitHomeworkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResultHomeworkSubmissionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitHomework(homeworkId, submitHomeworkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfileControllerApi.submitHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProfileControllerApi - factory interface
 */
export const ProfileControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProfileControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ProfileControllerApiGenerateHomeworkUploadUrlRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateHomeworkUploadUrl(requestParameters: ProfileControllerApiGenerateHomeworkUploadUrlRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultPresignedUrlDto> {
            return localVarFp.generateHomeworkUploadUrl(requestParameters.homeworkId, requestParameters.fileName, requestParameters.contentType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetAttendanceHistoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendanceHistory(requestParameters: ProfileControllerApiGetAttendanceHistoryRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultListAttendanceRecordDto> {
            return localVarFp.getAttendanceHistory(requestParameters.studentId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetAttendanceSummaryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAttendanceSummary(requestParameters: ProfileControllerApiGetAttendanceSummaryRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultAttendanceSummaryDto> {
            return localVarFp.getAttendanceSummary(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<ApiResultUserProfileDto> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetDashboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboard(requestParameters: ProfileControllerApiGetDashboardRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultDashboardDto> {
            return localVarFp.getDashboard(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetFeeLedgerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeeLedger(requestParameters: ProfileControllerApiGetFeeLedgerRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultStudentLedgerDto> {
            return localVarFp.getFeeLedger(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetHomeworkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHomework(requestParameters: ProfileControllerApiGetHomeworkRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultHomeworkListDto> {
            return localVarFp.getHomework(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetHomeworkSubmissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHomeworkSubmission(requestParameters: ProfileControllerApiGetHomeworkSubmissionRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultHomeworkSubmissionDto> {
            return localVarFp.getHomeworkSubmission(requestParameters.homeworkId, requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLinkedStudents(options?: RawAxiosRequestConfig): AxiosPromise<ApiResultListLinkedStudentDto> {
            return localVarFp.getLinkedStudents(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetResultsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResults(requestParameters: ProfileControllerApiGetResultsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultResultsDto> {
            return localVarFp.getResults(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiGetTimetableRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimetable(requestParameters: ProfileControllerApiGetTimetableRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultTimetableDto> {
            return localVarFp.getTimetable(requestParameters.studentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileControllerApiSubmitHomeworkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitHomework(requestParameters: ProfileControllerApiSubmitHomeworkRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResultHomeworkSubmissionDto> {
            return localVarFp.submitHomework(requestParameters.homeworkId, requestParameters.submitHomeworkRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for generateHomeworkUploadUrl operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGenerateHomeworkUploadUrlRequest {
    readonly homeworkId: number

    readonly fileName: string

    readonly contentType: string
}

/**
 * Request parameters for getAttendanceHistory operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetAttendanceHistoryRequest {
    readonly studentId?: number

    readonly startDate?: string

    readonly endDate?: string
}

/**
 * Request parameters for getAttendanceSummary operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetAttendanceSummaryRequest {
    readonly studentId?: number
}

/**
 * Request parameters for getDashboard operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetDashboardRequest {
    readonly studentId?: number
}

/**
 * Request parameters for getFeeLedger operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetFeeLedgerRequest {
    readonly studentId?: number
}

/**
 * Request parameters for getHomework operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetHomeworkRequest {
    readonly studentId?: number
}

/**
 * Request parameters for getHomeworkSubmission operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetHomeworkSubmissionRequest {
    readonly homeworkId: number

    readonly studentId?: number
}

/**
 * Request parameters for getResults operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetResultsRequest {
    readonly studentId?: number
}

/**
 * Request parameters for getTimetable operation in ProfileControllerApi.
 */
export interface ProfileControllerApiGetTimetableRequest {
    readonly studentId?: number
}

/**
 * Request parameters for submitHomework operation in ProfileControllerApi.
 */
export interface ProfileControllerApiSubmitHomeworkRequest {
    readonly homeworkId: number

    readonly submitHomeworkRequest: SubmitHomeworkRequest
}

/**
 * ProfileControllerApi - object-oriented interface
 */
export class ProfileControllerApi extends BaseAPI {
    /**
     * 
     * @param {ProfileControllerApiGenerateHomeworkUploadUrlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generateHomeworkUploadUrl(requestParameters: ProfileControllerApiGenerateHomeworkUploadUrlRequest, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).generateHomeworkUploadUrl(requestParameters.homeworkId, requestParameters.fileName, requestParameters.contentType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetAttendanceHistoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAttendanceHistory(requestParameters: ProfileControllerApiGetAttendanceHistoryRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getAttendanceHistory(requestParameters.studentId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetAttendanceSummaryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAttendanceSummary(requestParameters: ProfileControllerApiGetAttendanceSummaryRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getAttendanceSummary(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDashboard(requestParameters: ProfileControllerApiGetDashboardRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getDashboard(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetFeeLedgerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFeeLedger(requestParameters: ProfileControllerApiGetFeeLedgerRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getFeeLedger(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetHomeworkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHomework(requestParameters: ProfileControllerApiGetHomeworkRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getHomework(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetHomeworkSubmissionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHomeworkSubmission(requestParameters: ProfileControllerApiGetHomeworkSubmissionRequest, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getHomeworkSubmission(requestParameters.homeworkId, requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLinkedStudents(options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getLinkedStudents(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getResults(requestParameters: ProfileControllerApiGetResultsRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getResults(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiGetTimetableRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTimetable(requestParameters: ProfileControllerApiGetTimetableRequest = {}, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).getTimetable(requestParameters.studentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileControllerApiSubmitHomeworkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitHomework(requestParameters: ProfileControllerApiSubmitHomeworkRequest, options?: RawAxiosRequestConfig) {
        return ProfileControllerApiFp(this.configuration).submitHomework(requestParameters.homeworkId, requestParameters.submitHomeworkRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

