/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RoutineRequest } from '../models';
// @ts-ignore
import type { RoutineResponse } from '../models';
/**
 * RoutineControllerApi - axios parameter creator
 */
export const RoutineControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RoutineRequest} routineRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignSlot: async (routineRequest: RoutineRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'routineRequest' is not null or undefined
            assertParamExists('assignSlot', 'routineRequest', routineRequest)
            const localVarPath = `/api/academics/routine`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(routineRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearSlot: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('clearSlot', 'id', id)
            const localVarPath = `/api/academics/routine/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} classId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoutine: async (classId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('getRoutine', 'classId', classId)
            const localVarPath = `/api/academics/routine`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (classId !== undefined) {
                localVarQueryParameter['classId'] = classId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoutineControllerApi - functional programming interface
 */
export const RoutineControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoutineControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RoutineRequest} routineRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignSlot(routineRequest: RoutineRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoutineResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignSlot(routineRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutineControllerApi.assignSlot']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async clearSlot(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.clearSlot(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutineControllerApi.clearSlot']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} classId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoutine(classId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RoutineResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoutine(classId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutineControllerApi.getRoutine']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoutineControllerApi - factory interface
 */
export const RoutineControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoutineControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {RoutineControllerApiAssignSlotRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignSlot(requestParameters: RoutineControllerApiAssignSlotRequest, options?: RawAxiosRequestConfig): AxiosPromise<RoutineResponse> {
            return localVarFp.assignSlot(requestParameters.routineRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoutineControllerApiClearSlotRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearSlot(requestParameters: RoutineControllerApiClearSlotRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.clearSlot(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoutineControllerApiGetRoutineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoutine(requestParameters: RoutineControllerApiGetRoutineRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<RoutineResponse>> {
            return localVarFp.getRoutine(requestParameters.classId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for assignSlot operation in RoutineControllerApi.
 */
export interface RoutineControllerApiAssignSlotRequest {
    readonly routineRequest: RoutineRequest
}

/**
 * Request parameters for clearSlot operation in RoutineControllerApi.
 */
export interface RoutineControllerApiClearSlotRequest {
    readonly id: number
}

/**
 * Request parameters for getRoutine operation in RoutineControllerApi.
 */
export interface RoutineControllerApiGetRoutineRequest {
    readonly classId: number
}

/**
 * RoutineControllerApi - object-oriented interface
 */
export class RoutineControllerApi extends BaseAPI {
    /**
     * 
     * @param {RoutineControllerApiAssignSlotRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignSlot(requestParameters: RoutineControllerApiAssignSlotRequest, options?: RawAxiosRequestConfig) {
        return RoutineControllerApiFp(this.configuration).assignSlot(requestParameters.routineRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoutineControllerApiClearSlotRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public clearSlot(requestParameters: RoutineControllerApiClearSlotRequest, options?: RawAxiosRequestConfig) {
        return RoutineControllerApiFp(this.configuration).clearSlot(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoutineControllerApiGetRoutineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoutine(requestParameters: RoutineControllerApiGetRoutineRequest, options?: RawAxiosRequestConfig) {
        return RoutineControllerApiFp(this.configuration).getRoutine(requestParameters.classId, options).then((request) => request(this.axios, this.basePath));
    }
}

