/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BootstrapAdminRequest } from '../models';
// @ts-ignore
import type { School } from '../models';
// @ts-ignore
import type { User } from '../models';
/**
 * SchoolControllerApi - axios parameter creator
 */
export const SchoolControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {BootstrapAdminRequest} bootstrapAdminRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bootstrapAdmin: async (schoolId: string, bootstrapAdminRequest: BootstrapAdminRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('bootstrapAdmin', 'schoolId', schoolId)
            // verify required parameter 'bootstrapAdminRequest' is not null or undefined
            assertParamExists('bootstrapAdmin', 'bootstrapAdminRequest', bootstrapAdminRequest)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/bootstrap-admin`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bootstrapAdminRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {School} school 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSchool: async (school: School, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'school' is not null or undefined
            assertParamExists('createSchool', 'school', school)
            const localVarPath = `/api/platform/v1/schools`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(school, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSchools: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/platform/v1/schools`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchoolById: async (schoolId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getSchoolById', 'schoolId', schoolId)
            const localVarPath = `/api/platform/v1/schools/{schoolId}`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transitionStatus: async (schoolId: string, body: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('transitionStatus', 'schoolId', schoolId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('transitionStatus', 'body', body)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/status-transition`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SchoolControllerApi - functional programming interface
 */
export const SchoolControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SchoolControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {BootstrapAdminRequest} bootstrapAdminRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bootstrapAdmin(schoolId: string, bootstrapAdminRequest: BootstrapAdminRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bootstrapAdmin(schoolId, bootstrapAdminRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolControllerApi.bootstrapAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {School} school 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSchool(school: School, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<School>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSchool(school, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolControllerApi.createSchool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSchools(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<School>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSchools(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolControllerApi.getAllSchools']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchoolById(schoolId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<School>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchoolById(schoolId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolControllerApi.getSchoolById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transitionStatus(schoolId: string, body: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<School>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transitionStatus(schoolId, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolControllerApi.transitionStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SchoolControllerApi - factory interface
 */
export const SchoolControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SchoolControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {SchoolControllerApiBootstrapAdminRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bootstrapAdmin(requestParameters: SchoolControllerApiBootstrapAdminRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.bootstrapAdmin(requestParameters.schoolId, requestParameters.bootstrapAdminRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SchoolControllerApiCreateSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSchool(requestParameters: SchoolControllerApiCreateSchoolRequest, options?: RawAxiosRequestConfig): AxiosPromise<School> {
            return localVarFp.createSchool(requestParameters.school, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSchools(options?: RawAxiosRequestConfig): AxiosPromise<Array<School>> {
            return localVarFp.getAllSchools(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SchoolControllerApiGetSchoolByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchoolById(requestParameters: SchoolControllerApiGetSchoolByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<School> {
            return localVarFp.getSchoolById(requestParameters.schoolId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SchoolControllerApiTransitionStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transitionStatus(requestParameters: SchoolControllerApiTransitionStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<School> {
            return localVarFp.transitionStatus(requestParameters.schoolId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for bootstrapAdmin operation in SchoolControllerApi.
 */
export interface SchoolControllerApiBootstrapAdminRequest {
    readonly schoolId: string

    readonly bootstrapAdminRequest: BootstrapAdminRequest
}

/**
 * Request parameters for createSchool operation in SchoolControllerApi.
 */
export interface SchoolControllerApiCreateSchoolRequest {
    readonly school: School
}

/**
 * Request parameters for getSchoolById operation in SchoolControllerApi.
 */
export interface SchoolControllerApiGetSchoolByIdRequest {
    readonly schoolId: string
}

/**
 * Request parameters for transitionStatus operation in SchoolControllerApi.
 */
export interface SchoolControllerApiTransitionStatusRequest {
    readonly schoolId: string

    readonly body: string
}

/**
 * SchoolControllerApi - object-oriented interface
 */
export class SchoolControllerApi extends BaseAPI {
    /**
     * 
     * @param {SchoolControllerApiBootstrapAdminRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bootstrapAdmin(requestParameters: SchoolControllerApiBootstrapAdminRequest, options?: RawAxiosRequestConfig) {
        return SchoolControllerApiFp(this.configuration).bootstrapAdmin(requestParameters.schoolId, requestParameters.bootstrapAdminRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SchoolControllerApiCreateSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSchool(requestParameters: SchoolControllerApiCreateSchoolRequest, options?: RawAxiosRequestConfig) {
        return SchoolControllerApiFp(this.configuration).createSchool(requestParameters.school, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllSchools(options?: RawAxiosRequestConfig) {
        return SchoolControllerApiFp(this.configuration).getAllSchools(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SchoolControllerApiGetSchoolByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSchoolById(requestParameters: SchoolControllerApiGetSchoolByIdRequest, options?: RawAxiosRequestConfig) {
        return SchoolControllerApiFp(this.configuration).getSchoolById(requestParameters.schoolId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SchoolControllerApiTransitionStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transitionStatus(requestParameters: SchoolControllerApiTransitionStatusRequest, options?: RawAxiosRequestConfig) {
        return SchoolControllerApiFp(this.configuration).transitionStatus(requestParameters.schoolId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

