/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SchoolOperationConfig } from '../models';
/**
 * SchoolOperationControllerApi - axios parameter creator
 */
export const SchoolOperationControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOperationConfig: async (schoolId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getOperationConfig', 'schoolId', schoolId)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/operations`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {SchoolOperationConfig} schoolOperationConfig 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOperationConfig: async (schoolId: string, schoolOperationConfig: SchoolOperationConfig, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('updateOperationConfig', 'schoolId', schoolId)
            // verify required parameter 'schoolOperationConfig' is not null or undefined
            assertParamExists('updateOperationConfig', 'schoolOperationConfig', schoolOperationConfig)
            const localVarPath = `/api/platform/v1/schools/{schoolId}/operations`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(schoolOperationConfig, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SchoolOperationControllerApi - functional programming interface
 */
export const SchoolOperationControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SchoolOperationControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOperationConfig(schoolId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolOperationConfig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOperationConfig(schoolId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolOperationControllerApi.getOperationConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {SchoolOperationConfig} schoolOperationConfig 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOperationConfig(schoolId: string, schoolOperationConfig: SchoolOperationConfig, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolOperationConfig>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOperationConfig(schoolId, schoolOperationConfig, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchoolOperationControllerApi.updateOperationConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SchoolOperationControllerApi - factory interface
 */
export const SchoolOperationControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SchoolOperationControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {SchoolOperationControllerApiGetOperationConfigRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOperationConfig(requestParameters: SchoolOperationControllerApiGetOperationConfigRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchoolOperationConfig> {
            return localVarFp.getOperationConfig(requestParameters.schoolId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SchoolOperationControllerApiUpdateOperationConfigRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOperationConfig(requestParameters: SchoolOperationControllerApiUpdateOperationConfigRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchoolOperationConfig> {
            return localVarFp.updateOperationConfig(requestParameters.schoolId, requestParameters.schoolOperationConfig, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getOperationConfig operation in SchoolOperationControllerApi.
 */
export interface SchoolOperationControllerApiGetOperationConfigRequest {
    readonly schoolId: string
}

/**
 * Request parameters for updateOperationConfig operation in SchoolOperationControllerApi.
 */
export interface SchoolOperationControllerApiUpdateOperationConfigRequest {
    readonly schoolId: string

    readonly schoolOperationConfig: SchoolOperationConfig
}

/**
 * SchoolOperationControllerApi - object-oriented interface
 */
export class SchoolOperationControllerApi extends BaseAPI {
    /**
     * 
     * @param {SchoolOperationControllerApiGetOperationConfigRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOperationConfig(requestParameters: SchoolOperationControllerApiGetOperationConfigRequest, options?: RawAxiosRequestConfig) {
        return SchoolOperationControllerApiFp(this.configuration).getOperationConfig(requestParameters.schoolId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SchoolOperationControllerApiUpdateOperationConfigRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateOperationConfig(requestParameters: SchoolOperationControllerApiUpdateOperationConfigRequest, options?: RawAxiosRequestConfig) {
        return SchoolOperationControllerApiFp(this.configuration).updateOperationConfig(requestParameters.schoolId, requestParameters.schoolOperationConfig, options).then((request) => request(this.axios, this.basePath));
    }
}

