/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SchoolSubscription } from '../models';
// @ts-ignore
import type { SubscriptionPlan } from '../models';
/**
 * SubscriptionControllerApi - axios parameter creator
 */
export const SubscriptionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {string} planId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignPlan: async (schoolId: string, planId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('assignPlan', 'schoolId', schoolId)
            // verify required parameter 'planId' is not null or undefined
            assertParamExists('assignPlan', 'planId', planId)
            const localVarPath = `/api/platform/v1/subscriptions/assign/{schoolId}`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (planId !== undefined) {
                localVarQueryParameter['planId'] = planId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SubscriptionPlan} subscriptionPlan 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlan: async (subscriptionPlan: SubscriptionPlan, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriptionPlan' is not null or undefined
            assertParamExists('createPlan', 'subscriptionPlan', subscriptionPlan)
            const localVarPath = `/api/platform/v1/subscriptions/plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriptionPlan, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActiveSubscription: async (schoolId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schoolId' is not null or undefined
            assertParamExists('getActiveSubscription', 'schoolId', schoolId)
            const localVarPath = `/api/platform/v1/subscriptions/active/{schoolId}`
                .replace(`{${"schoolId"}}`, encodeURIComponent(String(schoolId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPlans: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/platform/v1/subscriptions/plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscriptionControllerApi - functional programming interface
 */
export const SubscriptionControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubscriptionControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} schoolId 
         * @param {string} planId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignPlan(schoolId: string, planId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolSubscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignPlan(schoolId, planId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionControllerApi.assignPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SubscriptionPlan} subscriptionPlan 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPlan(subscriptionPlan: SubscriptionPlan, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionPlan>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPlan(subscriptionPlan, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionControllerApi.createPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} schoolId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getActiveSubscription(schoolId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchoolSubscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getActiveSubscription(schoolId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionControllerApi.getActiveSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllPlans(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SubscriptionPlan>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllPlans(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionControllerApi.getAllPlans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubscriptionControllerApi - factory interface
 */
export const SubscriptionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubscriptionControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {SubscriptionControllerApiAssignPlanRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignPlan(requestParameters: SubscriptionControllerApiAssignPlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchoolSubscription> {
            return localVarFp.assignPlan(requestParameters.schoolId, requestParameters.planId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SubscriptionControllerApiCreatePlanRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlan(requestParameters: SubscriptionControllerApiCreatePlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionPlan> {
            return localVarFp.createPlan(requestParameters.subscriptionPlan, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SubscriptionControllerApiGetActiveSubscriptionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getActiveSubscription(requestParameters: SubscriptionControllerApiGetActiveSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchoolSubscription> {
            return localVarFp.getActiveSubscription(requestParameters.schoolId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPlans(options?: RawAxiosRequestConfig): AxiosPromise<Array<SubscriptionPlan>> {
            return localVarFp.getAllPlans(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for assignPlan operation in SubscriptionControllerApi.
 */
export interface SubscriptionControllerApiAssignPlanRequest {
    readonly schoolId: string

    readonly planId: string
}

/**
 * Request parameters for createPlan operation in SubscriptionControllerApi.
 */
export interface SubscriptionControllerApiCreatePlanRequest {
    readonly subscriptionPlan: SubscriptionPlan
}

/**
 * Request parameters for getActiveSubscription operation in SubscriptionControllerApi.
 */
export interface SubscriptionControllerApiGetActiveSubscriptionRequest {
    readonly schoolId: string
}

/**
 * SubscriptionControllerApi - object-oriented interface
 */
export class SubscriptionControllerApi extends BaseAPI {
    /**
     * 
     * @param {SubscriptionControllerApiAssignPlanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignPlan(requestParameters: SubscriptionControllerApiAssignPlanRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionControllerApiFp(this.configuration).assignPlan(requestParameters.schoolId, requestParameters.planId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SubscriptionControllerApiCreatePlanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPlan(requestParameters: SubscriptionControllerApiCreatePlanRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionControllerApiFp(this.configuration).createPlan(requestParameters.subscriptionPlan, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SubscriptionControllerApiGetActiveSubscriptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getActiveSubscription(requestParameters: SubscriptionControllerApiGetActiveSubscriptionRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionControllerApiFp(this.configuration).getActiveSubscription(requestParameters.schoolId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllPlans(options?: RawAxiosRequestConfig) {
        return SubscriptionControllerApiFp(this.configuration).getAllPlans(options).then((request) => request(this.axios, this.basePath));
    }
}

