/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TeacherRequest } from '../models';
// @ts-ignore
import type { TeacherResponse } from '../models';
/**
 * TeacherControllerApi - axios parameter creator
 */
export const TeacherControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TeacherRequest} teacherRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeacher: async (teacherRequest: TeacherRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teacherRequest' is not null or undefined
            assertParamExists('createTeacher', 'teacherRequest', teacherRequest)
            const localVarPath = `/api/academics/teachers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teacherRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTeacher: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTeacher', 'id', id)
            const localVarPath = `/api/academics/teachers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTeachers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/academics/teachers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeacherById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTeacherById', 'id', id)
            const localVarPath = `/api/academics/teachers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {TeacherRequest} teacherRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeacher: async (id: number, teacherRequest: TeacherRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTeacher', 'id', id)
            // verify required parameter 'teacherRequest' is not null or undefined
            assertParamExists('updateTeacher', 'teacherRequest', teacherRequest)
            const localVarPath = `/api/academics/teachers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teacherRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeacherControllerApi - functional programming interface
 */
export const TeacherControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeacherControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TeacherRequest} teacherRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTeacher(teacherRequest: TeacherRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeacherResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTeacher(teacherRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeacherControllerApi.createTeacher']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTeacher(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTeacher(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeacherControllerApi.deleteTeacher']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllTeachers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TeacherResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllTeachers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeacherControllerApi.getAllTeachers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeacherById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeacherResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeacherById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeacherControllerApi.getTeacherById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {TeacherRequest} teacherRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTeacher(id: number, teacherRequest: TeacherRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeacherResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTeacher(id, teacherRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeacherControllerApi.updateTeacher']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TeacherControllerApi - factory interface
 */
export const TeacherControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeacherControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {TeacherControllerApiCreateTeacherRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeacher(requestParameters: TeacherControllerApiCreateTeacherRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeacherResponse> {
            return localVarFp.createTeacher(requestParameters.teacherRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TeacherControllerApiDeleteTeacherRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTeacher(requestParameters: TeacherControllerApiDeleteTeacherRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTeacher(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllTeachers(options?: RawAxiosRequestConfig): AxiosPromise<Array<TeacherResponse>> {
            return localVarFp.getAllTeachers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TeacherControllerApiGetTeacherByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeacherById(requestParameters: TeacherControllerApiGetTeacherByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeacherResponse> {
            return localVarFp.getTeacherById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TeacherControllerApiUpdateTeacherRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTeacher(requestParameters: TeacherControllerApiUpdateTeacherRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeacherResponse> {
            return localVarFp.updateTeacher(requestParameters.id, requestParameters.teacherRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTeacher operation in TeacherControllerApi.
 */
export interface TeacherControllerApiCreateTeacherRequest {
    readonly teacherRequest: TeacherRequest
}

/**
 * Request parameters for deleteTeacher operation in TeacherControllerApi.
 */
export interface TeacherControllerApiDeleteTeacherRequest {
    readonly id: number
}

/**
 * Request parameters for getTeacherById operation in TeacherControllerApi.
 */
export interface TeacherControllerApiGetTeacherByIdRequest {
    readonly id: number
}

/**
 * Request parameters for updateTeacher operation in TeacherControllerApi.
 */
export interface TeacherControllerApiUpdateTeacherRequest {
    readonly id: number

    readonly teacherRequest: TeacherRequest
}

/**
 * TeacherControllerApi - object-oriented interface
 */
export class TeacherControllerApi extends BaseAPI {
    /**
     * 
     * @param {TeacherControllerApiCreateTeacherRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTeacher(requestParameters: TeacherControllerApiCreateTeacherRequest, options?: RawAxiosRequestConfig) {
        return TeacherControllerApiFp(this.configuration).createTeacher(requestParameters.teacherRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TeacherControllerApiDeleteTeacherRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTeacher(requestParameters: TeacherControllerApiDeleteTeacherRequest, options?: RawAxiosRequestConfig) {
        return TeacherControllerApiFp(this.configuration).deleteTeacher(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllTeachers(options?: RawAxiosRequestConfig) {
        return TeacherControllerApiFp(this.configuration).getAllTeachers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TeacherControllerApiGetTeacherByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTeacherById(requestParameters: TeacherControllerApiGetTeacherByIdRequest, options?: RawAxiosRequestConfig) {
        return TeacherControllerApiFp(this.configuration).getTeacherById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TeacherControllerApiUpdateTeacherRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTeacher(requestParameters: TeacherControllerApiUpdateTeacherRequest, options?: RawAxiosRequestConfig) {
        return TeacherControllerApiFp(this.configuration).updateTeacher(requestParameters.id, requestParameters.teacherRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

