/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SchoolClass } from './school-class';
// May contain unused imports in some cases
// @ts-ignore
import type { Student } from './student';

export interface AttendanceRecord {
    'createdAt'?: string;
    'updatedAt'?: string;
    'id'?: number;
    'student'?: Student;
    'schoolClass'?: SchoolClass;
    'date'?: string;
    'status'?: AttendanceRecordStatusEnum;
    'remarks'?: string;
    'markedBy'?: string;
    'modifiedBy'?: string;
    'modified'?: boolean;
}

export const AttendanceRecordStatusEnum = {
    Present: 'PRESENT',
    Absent: 'ABSENT',
    Late: 'LATE',
    Excused: 'EXCUSED',
    Holiday: 'HOLIDAY'
} as const;

export type AttendanceRecordStatusEnum = typeof AttendanceRecordStatusEnum[keyof typeof AttendanceRecordStatusEnum];


