/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ImportJob {
    'createdAt'?: string;
    'updatedAt'?: string;
    'id'?: string;
    'schoolId': string;
    'type'?: ImportJobTypeEnum;
    'status'?: ImportJobStatusEnum;
    'fileUrl'?: string;
    'errorReportUrl'?: string;
    'totalRecords'?: number;
    'processedRecords'?: number;
    'failedRecords'?: number;
}

export const ImportJobTypeEnum = {
    Student: 'STUDENT',
    Teacher: 'TEACHER',
    Parent: 'PARENT'
} as const;

export type ImportJobTypeEnum = typeof ImportJobTypeEnum[keyof typeof ImportJobTypeEnum];
export const ImportJobStatusEnum = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    PartiallyCompleted: 'PARTIALLY_COMPLETED'
} as const;

export type ImportJobStatusEnum = typeof ImportJobStatusEnum[keyof typeof ImportJobStatusEnum];


