/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface LiveLocationDto {
    'vehicleId'?: number;
    'vehicleNumber'?: string;
    'routeId'?: number;
    'routeName'?: string;
    'latitude'?: number;
    'longitude'?: number;
    'speedKmh'?: number;
    'heading'?: number;
    'capturedAt'?: string;
    'receivedAt'?: string;
    'secondsSinceLastUpdate'?: number;
    'stalenessMessage'?: string;
    'accuracyMeters'?: number;
    'currentTripId'?: number;
    'tripStatus'?: string;
    'stale'?: boolean;
}

