/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MarkAttendanceRequest {
    'studentId'?: number;
    'classId'?: number;
    'date'?: string;
    'status'?: MarkAttendanceRequestStatusEnum;
    'remarks'?: string;
}

export const MarkAttendanceRequestStatusEnum = {
    Present: 'PRESENT',
    Absent: 'ABSENT',
    Late: 'LATE',
    Excused: 'EXCUSED',
    Holiday: 'HOLIDAY'
} as const;

export type MarkAttendanceRequestStatusEnum = typeof MarkAttendanceRequestStatusEnum[keyof typeof MarkAttendanceRequestStatusEnum];


