/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AttendanceSummaryDto } from './attendance-summary-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ResultSummaryDto } from './result-summary-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { StudentProfileDto } from './student-profile-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SubjectMarkDto } from './subject-mark-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TermDetailsDto } from './term-details-dto';

export interface ReportCardDataDto {
    'student'?: StudentProfileDto;
    'term'?: TermDetailsDto;
    'attendance'?: AttendanceSummaryDto;
    'academics'?: Array<SubjectMarkDto>;
    'result'?: ResultSummaryDto;
}

