/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Role {
    'id'?: number;
    'name'?: RoleNameEnum;
}

export const RoleNameEnum = {
    RoleUser: 'ROLE_USER',
    RoleAdmin: 'ROLE_ADMIN',
    RoleTeacher: 'ROLE_TEACHER',
    RoleStudent: 'ROLE_STUDENT',
    RoleParent: 'ROLE_PARENT'
} as const;

export type RoleNameEnum = typeof RoleNameEnum[keyof typeof RoleNameEnum];


