/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocalTime } from './local-time';

export interface RoutineRequest {
    'classId': number;
    'subjectId': number;
    'teacherId': number;
    'dayOfWeek': RoutineRequestDayOfWeekEnum;
    'period': number;
    'startTime'?: LocalTime;
    'endTime'?: LocalTime;
}

export const RoutineRequestDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;

export type RoutineRequestDayOfWeekEnum = typeof RoutineRequestDayOfWeekEnum[keyof typeof RoutineRequestDayOfWeekEnum];


