/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StopInfo } from './stop-info';
// May contain unused imports in some cases
// @ts-ignore
import type { TripInfo } from './trip-info';
// May contain unused imports in some cases
// @ts-ignore
import type { VehicleInfo } from './vehicle-info';

export interface RouteDetailsDto {
    'routeId'?: number;
    'routeName'?: string;
    'routeCode'?: string;
    'routeType'?: string;
    'estimatedDurationMinutes'?: number;
    'distanceKm'?: number;
    'vehicleInfo'?: VehicleInfo;
    'assignedStop'?: StopInfo;
    'stops'?: Array<StopInfo>;
    'currentTrip'?: TripInfo;
}

