/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionPlan } from './subscription-plan';

export interface SchoolSubscription {
    'createdAt'?: string;
    'updatedAt'?: string;
    'id'?: string;
    'schoolId': string;
    'plan': SubscriptionPlan;
    'startDate': string;
    'endDate'?: string;
    'status'?: SchoolSubscriptionStatusEnum;
}

export const SchoolSubscriptionStatusEnum = {
    Active: 'ACTIVE',
    Expired: 'EXPIRED',
    Cancelled: 'CANCELLED',
    PendingPayment: 'PENDING_PAYMENT'
} as const;

export type SchoolSubscriptionStatusEnum = typeof SchoolSubscriptionStatusEnum[keyof typeof SchoolSubscriptionStatusEnum];


