/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StopEtaDto } from './stop-eta-dto';

export interface StopsWithEtaResponse {
    'routeId'?: number;
    'routeName'?: string;
    'vehicleId'?: number;
    'vehicleNumber'?: string;
    'hasLiveTracking'?: boolean;
    'lastUpdateTime'?: string;
    'stops'?: Array<StopEtaDto>;
}

