/* tslint:disable */
/* eslint-disable */
/**
 * Sanchalak Mobile API
 * API documentation for Sanchalak Mobile Application (Parent/Student)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sanchalak.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Role } from './role';

export interface User {
    'createdAt'?: string;
    'updatedAt'?: string;
    'id'?: string;
    'name': string;
    'email': string;
    'mobileNumber'?: string;
    'password': string;
    'roles'?: Set<Role>;
}

